//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLeapWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iLeapRepoEntities : DbContext
    {
        public iLeapRepoEntities()
            : base("name=iLeapRepoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAKAFUL_MDL_AProductionScheduler> TAKAFUL_MDL_AProductionScheduler { get; set; }
        public virtual DbSet<TAKAFUL_MDL_MainenanceWorkOrderList> TAKAFUL_MDL_MainenanceWorkOrderList { get; set; }
        public virtual DbSet<TAKAFUL_MDL_Maintaintechnicianslist> TAKAFUL_MDL_Maintaintechnicianslist { get; set; }
        public virtual DbSet<TAKAFUL_MDL_MaintenanceAssetID> TAKAFUL_MDL_MaintenanceAssetID { get; set; }
        public virtual DbSet<TAKAFUL_MDL_MaintenanceEquipmentMaterials> TAKAFUL_MDL_MaintenanceEquipmentMaterials { get; set; }
        public virtual DbSet<TAKAFUL_MDL_MaintenanceWorkOrder> TAKAFUL_MDL_MaintenanceWorkOrder { get; set; }
    }
}
