//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLeapWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKAFUL_MDL_AProductionScheduler
    {
        public long Id { get; set; }
        public Nullable<long> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public Nullable<long> CRB { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReferenceNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> DaysNeededToManufacture1Unit { get; set; }
        public Nullable<long> QuantityNeeded { get; set; }
        public string MachineType { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> ExpectedManufactureFinishDate { get; set; }
        public Nullable<long> MachineCapacity { get; set; }
        public string ProductName_Value { get; set; }
        public string MachineType_Value { get; set; }
        public Nullable<long> DaysToProduceTotalQuantity { get; set; }
        public string MachineStatus_Value { get; set; }
        public string Instruction { get; set; }
        public string MachineStatus { get; set; }
        public string LineA { get; set; }
        public string LineB { get; set; }
        public string Comments { get; set; }
        public string LineStatus { get; set; }
        public string LineStatus2 { get; set; }
        public Nullable<System.DateTime> RescheduleDate { get; set; }
        public string LineStatus3 { get; set; }
        public string LineStatus4 { get; set; }
        public string InventoryStatus { get; set; }
        public Nullable<long> DelayedDays { get; set; }
        public string ProductionLossesCost { get; set; }
        public string sakthiemailhidden { get; set; }
        public string CustomerName_Value { get; set; }
        public Nullable<System.DateTime> RescheduledEndDate { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DaysToProduceTotalAmount { get; set; }
        public Nullable<decimal> ActualCycleTime { get; set; }
        public Nullable<decimal> IdealCycleTime { get; set; }
        public Nullable<long> Noofnondefects { get; set; }
        public Nullable<long> idealcycletimeint { get; set; }
        public Nullable<long> Quality { get; set; }
        public Nullable<long> PlannedMachineRunTime { get; set; }
        public Nullable<long> ActualMachineRunTIme { get; set; }
        public Nullable<long> totaltimein1day { get; set; }
        public Nullable<long> delaydays { get; set; }
        public Nullable<long> DeliveredQuantity { get; set; }
        public Nullable<long> Breakdown { get; set; }
    }
}
