//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLeapWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKAFUL_MDL_MainenanceWorkOrderList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAKAFUL_MDL_MainenanceWorkOrderList()
        {
            this.TAKAFUL_MDL_MaintenanceWorkOrder = new HashSet<TAKAFUL_MDL_MaintenanceWorkOrder>();
        }
    
        public long Id { get; set; }
        public Nullable<long> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public Nullable<long> CRB { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReferenceNumber { get; set; }
        public string Description { get; set; }
        public Nullable<long> TaskID { get; set; }
        public string JobDone { get; set; }
        public string ActionTaken { get; set; }
        public string JobDone_Value { get; set; }
        public string TechnicianName { get; set; }
        public string TechnicianNameList_Value { get; set; }
        public string TechnicianNameList { get; set; }
        public Nullable<decimal> TimeTaken { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<long> DaysTaken { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<decimal> temperatureAPI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKAFUL_MDL_MaintenanceWorkOrder> TAKAFUL_MDL_MaintenanceWorkOrder { get; set; }
    }
}
