//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLeapWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKAFUL_MDL_MaintenanceEquipmentMaterials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAKAFUL_MDL_MaintenanceEquipmentMaterials()
        {
            this.TAKAFUL_MDL_MaintenanceWorkOrder = new HashSet<TAKAFUL_MDL_MaintenanceWorkOrder>();
        }
    
        public long Id { get; set; }
        public Nullable<long> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public Nullable<long> CRB { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReferenceNumber { get; set; }
        public string EquipmentMaterial { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string NeedToPurchase { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public string NeedToPurchase_Value { get; set; }
        public Nullable<decimal> QuantityDouble { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKAFUL_MDL_MaintenanceWorkOrder> TAKAFUL_MDL_MaintenanceWorkOrder { get; set; }
    }
}
