//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLeapWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKAFUL_MDL_MaintenanceWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAKAFUL_MDL_MaintenanceWorkOrder()
        {
            this.TAKAFUL_MDL_MaintenanceEquipmentMaterials = new HashSet<TAKAFUL_MDL_MaintenanceEquipmentMaterials>();
            this.TAKAFUL_MDL_MainenanceWorkOrderList = new HashSet<TAKAFUL_MDL_MainenanceWorkOrderList>();
        }
    
        public long Id { get; set; }
        public Nullable<long> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public Nullable<long> CRB { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> ActualJobFinishDate { get; set; }
        public string AssetID { get; set; }
        public string AssignTechnician { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EquipmentLocationCode { get; set; }
        public string EquipmentName { get; set; }
        public string JobPlan { get; set; }
        public string MainCategory { get; set; }
        public string MaintenanceManagerComments { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.TimeSpan> ReportTime { get; set; }
        public string SafetyPlan { get; set; }
        public Nullable<System.DateTime> ScheduleEndDate { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.TimeSpan> TimeFinish { get; set; }
        public Nullable<System.TimeSpan> TimeStarted { get; set; }
        public Nullable<System.TimeSpan> TimeTaken { get; set; }
        public Nullable<decimal> TimeTakenDouble { get; set; }
        public Nullable<decimal> TotalEquipmentMaterialCost { get; set; }
        public string WorkType { get; set; }
        public string AssignTechnician_Value { get; set; }
        public string MainCategory_Value { get; set; }
        public string MaintenanceManagerComments_Value { get; set; }
        public string Priority_Value { get; set; }
        public string Status_Value { get; set; }
        public string WorkType_Value { get; set; }
        public string WorkOrderRequestorName { get; set; }
        public string MaintenanceRequestDescription { get; set; }
        public string Equipmentv2_Value { get; set; }
        public string Equipmentv2 { get; set; }
        public string Image { get; set; }
        public string SubCategory { get; set; }
        public string Image2 { get; set; }
        public string LineBImage { get; set; }
        public string emailkiruhiddenbcc { get; set; }
        public string emailsakthihidden { get; set; }
        public Nullable<decimal> ActualCycletime { get; set; }
        public Nullable<decimal> EquipmentIdealCycleTime { get; set; }
        public Nullable<decimal> TemperatureAPI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKAFUL_MDL_MaintenanceEquipmentMaterials> TAKAFUL_MDL_MaintenanceEquipmentMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKAFUL_MDL_MainenanceWorkOrderList> TAKAFUL_MDL_MainenanceWorkOrderList { get; set; }
    }
}
