//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLeapWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKAFUL_MDL_MaintenanceAssetID
    {
        public long Id { get; set; }
        public Nullable<long> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public Nullable<long> CRB { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Equipment { get; set; }
        public string AssetID { get; set; }
        public string EquipmentLocationCode { get; set; }
        public string EquipmentSubCategory { get; set; }
        public string SerialNumber { get; set; }
    }
}
